name: struct
development: true
port: 3000
jwt_secret: qwertyuiopasdfghjklzxcvbnm123456
log_level: WARN 
ssl:
  key: /path/to/key
  cert: /path/to/certificate

redis:
  # host: host.docker.internal 
  host: localhost
  username: redis
  password: 1234
  port: 6379
  db: 1
  use_tls: true


postgres:
  username: doadmin
  password : AVNS_-OK3KDjBah18nx3cALr
  host: db-postgresql-fra1-42722-do-user-9369539-0.b.db.ondigitalocean.com
  port: 25060
  database: defaultdb
  sslmode: require

prometheus:
  path: /metrics
  namespace: v
  enabled: true
  
livekit:
  host: xxx
  api_key: xxx
  password: xxx
  setting: ./livekit.yaml


