name: struct
development: true
port: 3000
jwt_secret: qwertyuiopasdfghjklzxcvbnm123456
log_level: WARN 
ssl:
  key: /path/to/key
  cert: /path/to/certificate

redis:
  # host: host.docker.internal 
  host: localhost
  username: redis
  password: 1234
  port: 5432
  db: 1
  use_tls: true


sqlite: ./dev.db

prometheus:
  path: /metrics
  namespace: v
  enabled: true
  
livekit:
  host: xxx
  api_key: devkey
  secret: secret
  setting: ./livekit.yaml


