version: "3"
services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: struct 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: struct
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default
  redis:
    image: redis:6.0.9
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - default
  struct:
    build: .
    restart: always
    environment:
      POSTGRES_USER: struct 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: struct
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      REDIS_POOL_SIZE: 10
      REDIS_POOL_TIMEOUT: 10
      REDIS_POOL_IDLE_TIMEOUT: 10
  
    ports:
      - 8080:8080
    networks:
      - default
  # livekit:
  # implemet livekit server 

networks:
  default:
    external:
      name: struct
  