# This workflow will build a Golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install Dependencies
        run: go get -v -t -d ./...
      
      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
          
      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o ./out ./cmd/

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./out
